SELECT
 -- SUITE_NAME, EXECUTION_ID, TEST_NAME,
 XMLELEMENT(NAME "testcase",
  XMLATTRIBUTES(
   TEST_NAME AS "name",
   '0' AS "assertions",
   SUITE_NAME || '.' || TEST_NAME AS "classname",
   DURATION/1000 AS "time"
  ),
  CASE
   WHEN FINAL_STATE = 'Unstarted'
    THEN XMLELEMENT(NAME "skipped")
   WHEN FINAL_STATE = 'Error'
    THEN XMLELEMENT(NAME "error")
   WHEN FINAL_STATE = 'Failed'
    THEN XMLELEMENT(NAME "failure")
  END,
  (
--   SELECT LISTAGG(MESSAGE, CHAR(13)) WITHIN GROUP (ORDER BY DATE)
   SELECT
    XMLELEMENT(NAME "system-out",
     XMLAGG(
       XMLTEXT(MESSAGE || CHAR(13))
     )
    )
   FROM DB2UNIT_EXAMPLE.REPORT_TESTS R2
   WHERE R2.SUITE_NAME = R.SUITE_NAME
   AND R2.EXECUTION_ID = R.EXECUTION_ID
   AND R2.TEST_NAME = R.TEST_NAME
  )
 ) XML
FROM DB2UNIT_2_BETA.RESULT_TESTS R;

