--#SET TERMINATOR @

/*
Copyright (c) 2014-2014 Andres Gomez Casanova (AngocA).

All rights reserved. This program and the accompanying materials
are made available under the terms of the Eclipse Public License v1.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v10.html -->

Contributors:
Andres Gomez Casanova - initial API and implementation.
*/

SET CURRENT SCHEMA TEST_DB2UNIT_ASSERTIONS @

SET PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM", DB2UNIT_1A, TEST_DB2UNIT @

/**
 * Tests for assertions.
 *
 * Version: 2014-05-01 1-Alpha
 * Author: Andres Gomez Casanova (AngocA)
 * Made in COLOMBIA.
 */

CREATE SCHEMA TEST_DB2UNIT_ASSERTIONS @

-- Tests that no message is inserted in the report when two strings are equals.
CREATE OR REPLACE PROCEDURE TEST_1 ()
 BEGIN
  DECLARE ACTUAL_MSG ANCHOR DB2UNIT_1A.EXECUTION_REPORTS.MESSAGE;
  DECLARE EXPECTED_MSG ANCHOR DB2UNIT_1A.EXECUTION_REPORTS.MESSAGE;
  DECLARE STR_1 ANCHOR DB2UNIT_1A.EXECUTION_REPORTS.MESSAGE;
  DECLARE STR_2 ANCHOR DB2UNIT_1A.EXECUTION_REPORTS.MESSAGE;

  SET EXPECTED_MSG = 'Message check';
  INSERT INTO TEST_DB2UNIT_ASSERTIONS.REPORT_TESTS VALUES
    (CURRENT TIMESTAMP, 0, -1, EXPECTED_MSG);
  SET STR_1 = 'String';
  SET STR_2 = 'String';
  CALL DB2UNIT.ASSERT(STR_1, STR_2);
  SELECT MESSAGE INTO ACTUAL_MSG
    FROM TEST_DB2UNIT_ASSERTIONS.REPORT_TESTS
    WHERE DATE = (SELECT MAX(DATE) FROM TEST_DB2UNIT_ASSERTIONS.REPORT_TESTS);

  CALL DB2UNIT.ASSERT(EXPECTED_MSG, ACTUAL_MSG);
  DELETE FROM TEST_DB2UNIT_ASSERTIONS.REPORT_TESTS
    WHERE EXECUTION = 0
    AND STATUS = -1
    AND MESSAGE = EXPECTED_MSG;
 END@

-- Test two different strings with same length.
CREATE OR REPLACE PROCEDURE TEST_2 ()
 BEGIN
  DECLARE ACTUAL_MSG ANCHOR DB2UNIT_1A.EXECUTION_REPORTS.MESSAGE;
  DECLARE EXPECTED_MSG ANCHOR DB2UNIT_1A.EXECUTION_REPORTS.MESSAGE;
  DECLARE STR_1 ANCHOR DB2UNIT_1A.EXECUTION_REPORTS.MESSAGE;
  DECLARE STR_2 ANCHOR DB2UNIT_1A.EXECUTION_REPORTS.MESSAGE;

  SET EXPECTED_MSG = 'The strings'' content is different';
  SET STR_1 = 'String1';
  SET STR_2 = 'String2';
  CALL DB2UNIT.ASSERT(STR_1, STR_2);
  SELECT MESSAGE INTO ACTUAL_MSG
    FROM TEST_DB2UNIT_ASSERTIONS.REPORT_TESTS;

  CALL DB2UNIT.ASSERT(EXPECTED_MSG, ACTUAL_MSG);
 END@

-- Test two different strings, the first being longer than the second one.
CREATE OR REPLACE PROCEDURE TEST_3 ()
 BEGIN
  DECLARE ACTUAL_MSG ANCHOR DB2UNIT_1A.EXECUTION_REPORTS.MESSAGE;
  DECLARE EXPECTED_MSG ANCHOR DB2UNIT_1A.EXECUTION_REPORTS.MESSAGE;
  DECLARE STR_1 ANCHOR DB2UNIT_1A.EXECUTION_REPORTS.MESSAGE;
  DECLARE STR_2 ANCHOR DB2UNIT_1A.EXECUTION_REPORTS.MESSAGE;

  SET EXPECTED_MSG = 'Strings have different length';
  SET STR_1 = 'String-LONG';
  SET STR_2 = 'String';
  CALL DB2UNIT.ASSERT(STR_1, STR_2);
  SELECT MESSAGE INTO ACTUAL_MSG
    FROM TEST_DB2UNIT_ASSERTIONS.REPORT_TESTS;

  CALL DB2UNIT.ASSERT(EXPECTED_MSG, ACTUAL_MSG);
 END@

-- Test two different strings, the second being longer than the first one.
CREATE OR REPLACE PROCEDURE TEST_3 ()
 BEGIN
  DECLARE ACTUAL_MSG ANCHOR DB2UNIT_1A.EXECUTION_REPORTS.MESSAGE;
  DECLARE EXPECTED_MSG ANCHOR DB2UNIT_1A.EXECUTION_REPORTS.MESSAGE;
  DECLARE STR_1 ANCHOR DB2UNIT_1A.EXECUTION_REPORTS.MESSAGE;
  DECLARE STR_2 ANCHOR DB2UNIT_1A.EXECUTION_REPORTS.MESSAGE;

  SET EXPECTED_MSG = 'Strings have different length';
  SET STR_1 = 'String';
  SET STR_2 = 'String-LONG';
  CALL DB2UNIT.ASSERT(STR_1, STR_2);
  SELECT MESSAGE INTO ACTUAL_MSG
    FROM TEST_DB2UNIT_ASSERTIONS.REPORT_TESTS;

  CALL DB2UNIT.ASSERT(EXPECTED_MSG, ACTUAL_MSG);
 END@

