--#SET TERMINATOR @

/*
 This file is part of db2unit: A unit testing framework for DB2 LUW.
 Copyright (C)  2014  Andres Gomez Casanova (@AngocA)

 db2unit is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 db2unit is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 Andres Gomez Casanova <angocaATyahooDOTcom>
*/

SET CURRENT SCHEMA TEST_DB2UNIT_EXECUTION @

SET PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM", DB2UNIT_1B, TEST_DB2UNIT_EXECUTION @

/**
 * Tests for Execute Tests.
 *
 * Version: 2014-04-30 1-Beta
 * Author: Andres Gomez Casanova (AngocA)
 * Made in COLOMBIA.
 */

-- Creates the given schema.
CREATE OR REPLACE PROCEDURE CREATE_SCHEMA_TABLE(
  IN SCH_NAME ANCHOR SYSCAT.SCHEMATA.SCHEMANAME
  )
 BEGIN
  DECLARE SENTENCE ANCHOR DB2UNIT_1B.MAX_VALUES.SENTENCE;
  DECLARE STMT STATEMENT;

  SET SENTENCE = 'CREATE SCHEMA ' || SCH_NAME ;
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
 END @

-- Drops the given schema and its table.
CREATE OR REPLACE PROCEDURE DROP_SCHEMA_TABLE(
  IN SCH_NAME ANCHOR SYSCAT.SCHEMATA.SCHEMANAME
  )
 BEGIN
  DECLARE SENTENCE ANCHOR DB2UNIT_1B.MAX_VALUES.SENTENCE;
  DECLARE STMT STATEMENT;
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42893' SET SENTENCE = '';
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42884' SET SENTENCE = '';
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' SET SENTENCE = '';

  SET SENTENCE = 'DROP TABLE ' || SCH_NAME || '.REPORT_TESTS';
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DROP SCHEMA ' || SCH_NAME || ' RESTRICT';
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
 END @

CALL SYSPROC.ADMIN_DROP_SCHEMA('TEST_DB2UNIT_EXECUTION_TEST_2', NULL, 
  'ERRORSCHEMA', 'ERRORTABLE_2') @
CALL SYSPROC.ADMIN_DROP_SCHEMA('TEST_DB2UNIT_EXECUTION_TEST_3', NULL, 
  'ERRORSCHEMA', 'ERRORTABLE_3') @
CALL SYSPROC.ADMIN_DROP_SCHEMA('TEST_DB2UNIT_EXECUTION_TEST_4', NULL, 
  'ERRORSCHEMA', 'ERRORTABLE_4') @
CALL SYSPROC.ADMIN_DROP_SCHEMA('TEST_DB2UNIT_EXECUTION_TEST_5', NULL, 
  'ERRORSCHEMA', 'ERRORTABLE_5') @
CALL SYSPROC.ADMIN_DROP_SCHEMA('TEST_DB2UNIT_EXECUTION_TEST_6_1234567890'
    || '1234567890123456789012345678901234567890123456789012345678901234567890'
    || '123456789012345678', NULL, 
  'ERRORSCHEMA', 'ERRORTABLE_6') @
CALL SYSPROC.ADMIN_DROP_SCHEMA('TEST_DB2UNIT_EXECUTION_TEST_7', NULL, 
  'ERRORSCHEMA', 'ERRORTABLE_7') @
CALL SYSPROC.ADMIN_DROP_SCHEMA('TEST_DB2UNIT_EXECUTION_TEST_8', NULL, 
  'ERRORSCHEMA', 'ERRORTABLE_8') @
CALL SYSPROC.ADMIN_DROP_SCHEMA('TEST_DB2UNIT_EXECUTION_TEST_9', NULL, 
  'ERRORSCHEMA', 'ERRORTABLE_9') @
CALL SYSPROC.ADMIN_DROP_SCHEMA('TEST_DB2UNIT_EXECUTION_TEST_10', NULL, 
  'ERRORSCHEMA', 'ERRORTABLE_10') @
CALL SYSPROC.ADMIN_DROP_SCHEMA('TEST_DB2UNIT_EXECUTION_TEST_11', NULL, 
  'ERRORSCHEMA', 'ERRORTABLE_11') @
CALL SYSPROC.ADMIN_DROP_SCHEMA('TEST_DB2UNIT_EXECUTION_TEST_12', NULL, 
  'ERRORSCHEMA', 'ERRORTABLE_12') @
CALL SYSPROC.ADMIN_DROP_SCHEMA('TEST_DB2UNIT_EXECUTION_TEST_13', NULL, 
  'ERRORSCHEMA', 'ERRORTABLE_13') @
CALL SYSPROC.ADMIN_DROP_SCHEMA('TEST_DB2UNIT_EXECUTION_TEST_14', NULL, 
  'ERRORSCHEMA', 'ERRORTABLE_14') @

-- Drops all tables and schemas.
CREATE OR REPLACE PROCEDURE ONE_TIME_TEAR_DOWN()
 BEGIN
  CALL DROP_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_2');
  CALL DROP_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_3');
  CALL DROP_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_4');
  CALL DROP_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_5');
  CALL DROP_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_6_12345678901234567890'
    || '1234567890123456789012345678901234567890123456789012345678901234567890'
    || '12345678');
  CALL DROP_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_7');
  CALL DROP_SCHEMA_TABLE('TEST_DB2UNIT_Execution_Test_8');
  CALL DROP_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_9');
  CALL DROP_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_10');
  CALL DROP_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_11');
  CALL DROP_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_12');
  CALL DROP_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_13');
  CALL DROP_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_14');
 END @

-- Creates the necessary schemas.
CREATE OR REPLACE PROCEDURE ONE_TIME_SETUP()
 BEGIN
  -- If a previous execution did not correclty finished.
  CALL ONE_TIME_TEAR_DOWN();

  CALL CREATE_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_2');
  CALL CREATE_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_3');
  CALL CREATE_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_4');
  CALL CREATE_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_5');
  CALL CREATE_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_6_12345678901234567890'
    || '1234567890123456789012345678901234567890123456789012345678901234567890'
    || '12345678');
  CALL CREATE_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_7');
  CALL CREATE_SCHEMA_TABLE('TEST_DB2UNIT_Execution_Test_8');
  CALL CREATE_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_9');
  CALL CREATE_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_10');
  CALL CREATE_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_11');
  CALL CREATE_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_12');
  CALL CREATE_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_13');
  CALL CREATE_SCHEMA_TABLE('TEST_DB2UNIT_EXECUTION_TEST_14');
 END @

-- Test the execution of a non-existent schema.
CREATE OR REPLACE PROCEDURE TEST_01()
 BEGIN
  DECLARE ACTUAL_MSG ANCHOR DB2UNIT_1B.EXECUTION_REPORTS.MESSAGE_REPORT;
  DECLARE EXPECTED_MSG ANCHOR DB2UNIT_1B.EXECUTION_REPORTS.MESSAGE_REPORT;
  DECLARE SCHEMA_NAME ANCHOR SYSCAT.SCHEMATA.SCHEMANAME;

  SET SCHEMA_NAME = 'NoSchema1                                                 '
    || '                                    ';
  SET EXPECTED_MSG = 'The given schema does not exists: ' || SCHEMA_NAME;
  CALL DB2UNIT_1B.DB2UNIT.RUN_SUITE(SCHEMA_NAME);
  COMMIT;
  SELECT MESSAGE_REPORT INTO ACTUAL_MSG
    FROM DB2UNIT_1B.EXECUTION_REPORTS
    WHERE DATE = (SELECT MAX(DATE) FROM DB2UNIT_1B.EXECUTION_REPORTS);

  DELETE FROM DB2UNIT_1B.EXECUTION_REPORTS
    WHERE DATE = (SELECT MAX(DATE) FROM DB2UNIT_1B.EXECUTION_REPORTS)
    AND MESSAGE_REPORT = EXPECTED_MSG;

  CALL DB2UNIT_1B.DB2UNIT.ASSERT_STRING_EQUALS(EXPECTED_MSG, ACTUAL_MSG);
 END@

-- Test the execution of a existent schema without problem.
CREATE OR REPLACE PROCEDURE TEST_02()
 BEGIN
  DECLARE ACTUAL_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE EXPECTED_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE SCHEMA_NAME ANCHOR SYSCAT.SCHEMATA.SCHEMANAME;
  DECLARE SENTENCE ANCHOR DB2UNIT_1B.MAX_VALUES.SENTENCE;
  DECLARE STMT STATEMENT;

  SET EXPECTED_MSG = '0 tests with errors';
  SET SCHEMA_NAME = 'TEST_DB2UNIT_EXECUTION_TEST_2';

  CALL DB2UNIT_1B.DB2UNIT.RUN_SUITE(SCHEMA_NAME);

  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE = ''Finishing execution''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;

  SET SENTENCE = 'SET ? = (SELECT MESSAGE '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS))';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT INTO ACTUAL_MSG;
  COMMIT;

  DELETE FROM DB2UNIT_1B.EXECUTION_REPORTS
    WHERE DATE = (SELECT MAX(DATE) FROM DB2UNIT_1B.EXECUTION_REPORTS)
    AND MESSAGE_REPORT LIKE 'Execution of TEST_DB2UNIT_EXECUTION_TEST_2 with %';
  DELETE FROM DB2UNIT_1B.EXECUTION_REPORTS
    WHERE DATE = (SELECT MAX(DATE) FROM DB2UNIT_1B.EXECUTION_REPORTS)
    AND MESSAGE_REPORT LIKE 'db2unit is licensed under the terms of the GPL v3';

  CALL DB2UNIT_1B.DB2UNIT.ASSERT_STRING_EQUALS(EXPECTED_MSG, ACTUAL_MSG);
 END@

-- Test the execution of a existent schema without table creation.
CREATE OR REPLACE PROCEDURE TEST_03()
 BEGIN
  DECLARE ACTUAL_MSG ANCHOR DB2UNIT_1B.EXECUTION_REPORTS.MESSAGE_REPORT;
  DECLARE EXPECTED_MSG ANCHOR DB2UNIT_1B.EXECUTION_REPORTS.MESSAGE_REPORT;
  DECLARE SCHEMA_NAME ANCHOR SYSCAT.SCHEMATA.SCHEMANAME;

  SET SCHEMA_NAME = 'TEST_DB2UNIT_EXECUTION_TEST_3';
  SET EXPECTED_MSG = 'The reports table already exist: ' || SCHEMA_NAME
    || '.REPORT_TESTS';

  CALL DB2UNIT_1B.DB2UNIT.RUN_SUITE(SCHEMA_NAME);
  COMMIT;
  CALL DB2UNIT_1B.DB2UNIT.RUN_SUITE(SCHEMA_NAME);
  COMMIT;
  SELECT MESSAGE_REPORT INTO ACTUAL_MSG
    FROM DB2UNIT_1B.EXECUTION_REPORTS
    WHERE DATE = (SELECT MAX(DATE) FROM DB2UNIT_1B.EXECUTION_REPORTS);

  CALL DB2UNIT_1B.DB2UNIT.ASSERT_STRING_EQUALS(EXPECTED_MSG, ACTUAL_MSG);
 END@

-- Tests that a report message persist even after a rollback
CREATE OR REPLACE PROCEDURE TEST_04()
 BEGIN
  DECLARE ID INT;
  DECLARE ACTUAL_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE EXPECTED_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE SCHEMA_NAME ANCHOR SYSCAT.SCHEMATA.SCHEMANAME;
  DECLARE SENTENCE ANCHOR DB2UNIT_1B.MAX_VALUES.SENTENCE;
  DECLARE STMT STATEMENT;
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' SET ID = 0;
  SET EXPECTED_MSG = '0 tests with errors';
  SET SCHEMA_NAME = 'TEST_DB2UNIT_EXECUTION_TEST_4';

  SET SENTENCE = 'CREATE OR REPLACE PROCEDURE ' || SCHEMA_NAME || '.TEST_4() '
    || 'BEGIN '
    || 'ROLLBACK; '
    || 'END ';
  CALL LOGGER.ERROR(0, SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  CALL DB2UNIT_1B.DB2UNIT.RUN_SUITE(SCHEMA_NAME);
  COMMIT;
  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE = ''Finishing execution''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;

  SET SENTENCE = 'SET ? = (SELECT MESSAGE '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS))';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT INTO ACTUAL_MSG;

  SET SENTENCE = 'DROP PROCEDURE ' || SCHEMA_NAME || '.TEST_4()';
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DROP TABLE ' || SCHEMA_NAME || '.REPORT_TESTS';
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;

  CALL DB2UNIT_1B.DB2UNIT.ASSERT_STRING_EQUALS(EXPECTED_MSG, ACTUAL_MSG);
 END @

-- Tests that a report message persist even after a commit
CREATE OR REPLACE PROCEDURE TEST_05()
 BEGIN
  DECLARE ID INT;
  DECLARE ACTUAL_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE EXPECTED_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE SCHEMA_NAME ANCHOR SYSCAT.SCHEMATA.SCHEMANAME;
  DECLARE SENTENCE ANCHOR DB2UNIT_1B.MAX_VALUES.SENTENCE;
  DECLARE STMT STATEMENT;
  SET EXPECTED_MSG = '0 tests with errors';
  SET SCHEMA_NAME = 'TEST_DB2UNIT_EXECUTION_TEST_5';

  SET SENTENCE = 'CREATE OR REPLACE PROCEDURE ' || SCHEMA_NAME || '.TEST_5() '
    || 'BEGIN '
    || 'COMMIT; '
    || 'END ';
  CALL LOGGER.ERROR(0, SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  CALL DB2UNIT_1B.DB2UNIT.RUN_SUITE(SCHEMA_NAME);
  COMMIT;
  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE = ''Finishing execution''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;

  SET SENTENCE = 'SET ? = (SELECT MESSAGE '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS))';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT INTO ACTUAL_MSG;

  SET SENTENCE = 'DROP PROCEDURE ' || SCHEMA_NAME || '.TEST_5()';
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DROP TABLE ' || SCHEMA_NAME || '.REPORT_TESTS';
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;

  CALL DB2UNIT_1B.DB2UNIT.ASSERT_STRING_EQUALS(EXPECTED_MSG, ACTUAL_MSG);
 END @

-- Test the execution of a existent schema with a very long name without
-- problem. This is the MAX name for a schema without generating problems.
CREATE OR REPLACE PROCEDURE TEST_06()
 BEGIN
  DECLARE ACTUAL_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE EXPECTED_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE SCHEMA_NAME ANCHOR SYSCAT.SCHEMATA.SCHEMANAME;
  DECLARE SENTENCE ANCHOR DB2UNIT_1B.MAX_VALUES.SENTENCE;
  DECLARE STMT STATEMENT;

  SET EXPECTED_MSG = '0 tests with errors';
  SET SCHEMA_NAME = 'TEST_DB2UNIT_EXECUTION_TEST_6_12345678901234567890'
    || '1234567890123456789012345678901234567890123456789012345678901234567890'
    || '123456789';

  CALL DB2UNIT_1B.DB2UNIT.RUN_SUITE(SCHEMA_NAME);

  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE = ''Finishing execution''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;

  SET SENTENCE = 'SET ? = (SELECT MESSAGE '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS))';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT INTO ACTUAL_MSG;
  COMMIT;

  CALL DB2UNIT_1B.DB2UNIT.ASSERT_STRING_EQUALS(EXPECTED_MSG, ACTUAL_MSG);
 END@

-- Test a string that is too long.
CREATE OR REPLACE PROCEDURE TEST_07()
 BEGIN
  DECLARE ACTUAL_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE EXPECTED_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE STR VARCHAR(1024);
  DECLARE SCHEMA_NAME ANCHOR SYSCAT.SCHEMATA.SCHEMANAME;
  DECLARE SENTENCE ANCHOR DB2UNIT_1B.MAX_VALUES.SENTENCE;
  DECLARE STMT STATEMENT;

  SET SCHEMA_NAME = 'TEST_DB2UNIT_EXECUTION_TEST_7';
  SET STR = '123456789012345678901234567890123456789012345678901234567890123456'
    || '78901234567890123456789012345678901234567890123456789012345678901234567'
    || '89012345678901234567890123456789012345678901234567890123456789012345678'
    || '90123456789012345678901234567890123456789012345678901234567890123456789'
    || '01234567890123456789012345678901234567890123456789012345678901234567890'
    || '12345678901234567890123456789012345678901234567890123456789012345678901'
    || '23456789012345678901234567890123456789012345678901234567890123456789012'
    || '34567890123456789012345678901234567890123456789012345678901234567890123'
    || '45678901234567890123456789012345678901234567890123456789012345678901234'
    || '56789012345678901234567890123456789012345678901234567890123456789012345'
    || '6789012345678901234567890';
  SET EXPECTED_MSG = 'String too long: "SQL0433N  Value ""1234567890123456789012'
    || '3456789012345678901234567890123456789" is too long.  SQLSTATE=22001   '
    || '"';
  SET SENTENCE = 'CREATE OR REPLACE PROCEDURE ' || SCHEMA_NAME || '.TEST_7() '
    || 'BEGIN '
    || 'CALL DB2UNIT.ASSERT_STRING_EQUALS(''' || STR || ''', '''');'
    || 'END ';
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;

  CALL DB2UNIT_1B.DB2UNIT.RUN_SUITE(SCHEMA_NAME);
  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE LIKE ''_ tests with errors''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE LIKE ''_ tests failed''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE LIKE ''_ tests passed''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE LIKE ''_ tests were executed''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE = ''Finishing execution''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;

  SET SENTENCE = 'SET ? = (SELECT MESSAGE '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS))';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT INTO ACTUAL_MSG;

  SET SENTENCE = 'DROP PROCEDURE ' || SCHEMA_NAME || '.TEST_7()';
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DROP TABLE ' || SCHEMA_NAME || '.REPORT_TESTS';
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;

  CALL DB2UNIT.ASSERT_STRING_EQUALS(EXPECTED_MSG, ACTUAL_MSG);
 END@

-- Test the execution of a existent schema without problem.
CREATE OR REPLACE PROCEDURE TEST_08()
 BEGIN
  DECLARE ACTUAL_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE EXPECTED_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE SCHEMA_NAME ANCHOR SYSCAT.SCHEMATA.SCHEMANAME;
  DECLARE SENTENCE ANCHOR DB2UNIT_1B.MAX_VALUES.SENTENCE;
  DECLARE STMT STATEMENT;

  SET EXPECTED_MSG = '0 tests with errors';
  SET SCHEMA_NAME = 'TEST_DB2UNIT_Execution_Test_8';

  CALL DB2UNIT_1B.DB2UNIT.RUN_SUITE(SCHEMA_NAME);

  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE = ''Finishing execution''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;

  SET SENTENCE = 'SET ? = (SELECT MESSAGE '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS))';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT INTO ACTUAL_MSG;
  COMMIT;

  DELETE FROM DB2UNIT_1B.EXECUTION_REPORTS
    WHERE DATE = (SELECT MAX(DATE) FROM DB2UNIT_1B.EXECUTION_REPORTS)
    AND MESSAGE_REPORT LIKE 'Execution of TEST_DB2UNIT_EXECUTION_TEST_2 with %';
  DELETE FROM DB2UNIT_1B.EXECUTION_REPORTS
    WHERE DATE = (SELECT MAX(DATE) FROM DB2UNIT_1B.EXECUTION_REPORTS)
    AND MESSAGE_REPORT LIKE 'db2unit is licensed under the terms of the GPL v3';

  CALL DB2UNIT_1B.DB2UNIT.ASSERT_STRING_EQUALS(EXPECTED_MSG, ACTUAL_MSG);
 END@

-- Test the execution of a existent schema without problem.
CREATE OR REPLACE PROCEDURE TEST_09()
 BEGIN
  DECLARE ACTUAL_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE EXPECTED_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE SCHEMA_NAME ANCHOR SYSCAT.SCHEMATA.SCHEMANAME;
  DECLARE SENTENCE ANCHOR DB2UNIT_1B.MAX_VALUES.SENTENCE;
  DECLARE STMT STATEMENT;

  SET EXPECTED_MSG = '0 tests with errors';
  SET SCHEMA_NAME = 'TEST_DB2UNIT_Execution_Test_9';

  CALL DB2UNIT_1B.DB2UNIT.RUN_SUITE(SCHEMA_NAME);

  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE = ''Finishing execution''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;

  SET SENTENCE = 'SET ? = (SELECT MESSAGE '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS))';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT INTO ACTUAL_MSG;
  COMMIT;

  DELETE FROM DB2UNIT_1B.EXECUTION_REPORTS
    WHERE DATE = (SELECT MAX(DATE) FROM DB2UNIT_1B.EXECUTION_REPORTS)
    AND MESSAGE_REPORT LIKE 'Execution of TEST_DB2UNIT_EXECUTION_TEST_2 with %';
  DELETE FROM DB2UNIT_1B.EXECUTION_REPORTS
    WHERE DATE = (SELECT MAX(DATE) FROM DB2UNIT_1B.EXECUTION_REPORTS)
    AND MESSAGE_REPORT LIKE 'db2unit is licensed under the terms of the GPL v3';

  CALL DB2UNIT_1B.DB2UNIT.ASSERT_STRING_EQUALS(EXPECTED_MSG, ACTUAL_MSG);
 END@

-- Tests that a test that throws a signal.
CREATE OR REPLACE PROCEDURE TEST_10()
 BEGIN
  DECLARE ID INT;
  DECLARE ACTUAL_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE EXPECTED_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE SCHEMA_NAME ANCHOR SYSCAT.SCHEMATA.SCHEMANAME;
  DECLARE SENTENCE ANCHOR DB2UNIT_1B.MAX_VALUES.SENTENCE;
  DECLARE SQLSTT VARCHAR(5);
  DECLARE STMT STATEMENT;
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' SET ID = 0;
  SET SQLSTT = '12345';
  SET EXPECTED_MSG = 'Exception: SQLCode-438-SQLState' || SQLSTT
    || '-SQL0438N  Application raised error or warning with diagnostic text: '
    || '"".  SQLSTATE=' || SQLSTT;
  SET SCHEMA_NAME = 'TEST_DB2UNIT_EXECUTION_TEST_10';

  SET SENTENCE = 'CREATE OR REPLACE PROCEDURE ' || SCHEMA_NAME || '.TEST_10() '
    || 'BEGIN '
    || '  SIGNAL SQLSTATE ''' || SQLSTT || '''; '
    || 'END ';
  CALL LOGGER.ERROR(0, SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  CALL DB2UNIT_1B.DB2UNIT.RUN_SUITE(SCHEMA_NAME);
  COMMIT;
  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE LIKE ''% tests with errors''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE LIKE ''% tests failed''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE LIKE ''% tests passed''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE LIKE ''% tests were executed''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE LIKE ''Finishing execution''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;

  SET SENTENCE = 'SET ? = (SELECT MESSAGE '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS))';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT INTO ACTUAL_MSG;

  SET SENTENCE = 'DROP PROCEDURE ' || SCHEMA_NAME || '.TEST_10()';
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DROP TABLE ' || SCHEMA_NAME || '.REPORT_TESTS';
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;

  CALL DB2UNIT_1B.DB2UNIT.ASSERT_STRING_EQUALS(EXPECTED_MSG, ACTUAL_MSG);
 END @

-- Tests that a test that throws a signal and register the test.
CREATE OR REPLACE PROCEDURE TEST_11()
 BEGIN
  DECLARE ID INT;
  DECLARE ACTUAL_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE EXPECTED_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE ACTUAL_MSG2 ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE EXPECTED_MSG2 ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE SCHEMA_NAME ANCHOR SYSCAT.SCHEMATA.SCHEMANAME;
  DECLARE SENTENCE ANCHOR DB2UNIT_1B.MAX_VALUES.SENTENCE;
  DECLARE SQLSTT VARCHAR(5);
  DECLARE STMT STATEMENT;
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' SET ID = 0;
  SET EXPECTED_MSG2 = 'TEST-11 MSG';
  SET SQLSTT = '67890';
  SET EXPECTED_MSG = 'Exception: SQLCode-438-SQLState' || SQLSTT
    || '-SQL0438N  Application raised error or warning with diagnostic text: '
    || '"".  SQLSTATE=' || SQLSTT;
  SET SCHEMA_NAME = 'TEST_DB2UNIT_EXECUTION_TEST_11';

  SET SENTENCE = 'CREATE OR REPLACE PROCEDURE ' || SCHEMA_NAME || '.TEST_11() '
    || 'BEGIN '
    || ' CALL DB2UNIT.REGISTER_MESSAGE(''' || EXPECTED_MSG2 || '''); '
    || '  SIGNAL SQLSTATE ''' || SQLSTT || '''; '
    || 'END ';
  CALL LOGGER.ERROR(0, SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  CALL DB2UNIT_1B.DB2UNIT.RUN_SUITE(SCHEMA_NAME);
  COMMIT;
  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE LIKE ''% tests with errors''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE LIKE ''% tests failed''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE LIKE ''% tests passed''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE LIKE ''% tests were executed''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE LIKE ''Finishing execution''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;

  SET SENTENCE = 'SET ? = (SELECT MESSAGE '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS))';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT INTO ACTUAL_MSG;

  SET SENTENCE = 'DELETE FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS) '
    || 'AND MESSAGE LIKE ''' || EXPECTED_MSG || '''';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;

  SET SENTENCE = 'SET ? = (SELECT MESSAGE '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS))';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT INTO ACTUAL_MSG2;

  SET SENTENCE = 'DROP PROCEDURE ' || SCHEMA_NAME || '.TEST_11()';
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DROP TABLE ' || SCHEMA_NAME || '.REPORT_TESTS';
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;

  CALL DB2UNIT_1B.DB2UNIT.ASSERT_STRING_EQUALS(EXPECTED_MSG, ACTUAL_MSG);
  CALL DB2UNIT_1B.DB2UNIT.ASSERT_STRING_EQUALS(EXPECTED_MSG2, ACTUAL_MSG2);
 END @

-- Tests that executes just one SP from a suite with multiple tests.
CREATE OR REPLACE PROCEDURE TEST_12()
 BEGIN
  DECLARE ID INT;
  DECLARE ACTUAL_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE EXPECTED_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE SCHEMA_NAME ANCHOR SYSCAT.SCHEMATA.SCHEMANAME;
  DECLARE SENTENCE ANCHOR DB2UNIT_1B.MAX_VALUES.SENTENCE;
  DECLARE STMT STATEMENT;
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' SET ID = 0;
  SET EXPECTED_MSG = '1 tests were executed';
  SET SCHEMA_NAME = 'TEST_DB2UNIT_EXECUTION_TEST_12';

  SET SENTENCE = 'CREATE OR REPLACE PROCEDURE ' || SCHEMA_NAME || '.TEST_12a() '
    || 'BEGIN '
    || 'END ';
  CALL LOGGER.ERROR(0, SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'CREATE OR REPLACE PROCEDURE ' || SCHEMA_NAME || '.TEST_12b() '
    || 'BEGIN '
    || 'END ';
  CALL LOGGER.ERROR(0, SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  CALL DB2UNIT_1B.DB2UNIT.RUN_SUITE(SCHEMA_NAME, PROC_NAME => 'TEST_12b');

  SET SENTENCE = 'SET ? = (SELECT MESSAGE '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE MESSAGE LIKE ''% tests were executed'')';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT INTO ACTUAL_MSG;

  SET SENTENCE = 'DROP PROCEDURE ' || SCHEMA_NAME || '.TEST_12a()';
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DROP PROCEDURE ' || SCHEMA_NAME || '.TEST_12b()';
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DROP TABLE ' || SCHEMA_NAME || '.REPORT_TESTS';
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;

  CALL DB2UNIT_1B.DB2UNIT.ASSERT_STRING_EQUALS(EXPECTED_MSG, ACTUAL_MSG);
 END @

-- Tests that calls a given test without the same case.
CREATE OR REPLACE PROCEDURE TEST_13()
 BEGIN
  DECLARE ID INT;
  DECLARE ACTUAL_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE EXPECTED_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE SCHEMA_NAME ANCHOR SYSCAT.SCHEMATA.SCHEMANAME;
  DECLARE SENTENCE ANCHOR DB2UNIT_1B.MAX_VALUES.SENTENCE;
  DECLARE STMT STATEMENT;
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' SET ID = 0;
  SET EXPECTED_MSG = '1 tests were executed';
  SET SCHEMA_NAME = 'TEST_DB2UNIT_EXECUTION_TEST_13';

  SET SENTENCE = 'CREATE OR REPLACE PROCEDURE ' || SCHEMA_NAME || '.TEST_13A() '
    || 'BEGIN '
    || 'END ';
  CALL LOGGER.ERROR(0, SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  CALL DB2UNIT_1B.DB2UNIT.RUN_SUITE(SCHEMA_NAME, PROC_NAME => 'Test_13a');

  SET SENTENCE = 'SET ? = (SELECT MESSAGE '
    || 'FROM ' || SCHEMA_NAME || '.REPORT_TESTS '
    || 'WHERE MESSAGE LIKE ''% tests were executed'')';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT INTO ACTUAL_MSG;

  SET SENTENCE = 'DROP PROCEDURE ' || SCHEMA_NAME || '.TEST_13A()';
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;
  SET SENTENCE = 'DROP TABLE ' || SCHEMA_NAME || '.REPORT_TESTS';
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT;

  CALL DB2UNIT_1B.DB2UNIT.ASSERT_STRING_EQUALS(EXPECTED_MSG, ACTUAL_MSG);
 END @

-- Tests that calls a given test without the same case.
CREATE OR REPLACE PROCEDURE TEST_14()
 BEGIN
  DECLARE ID INT;
  DECLARE ACTUAL_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE EXPECTED_MSG ANCHOR DB2UNIT_1B.REPORT_TESTS.MESSAGE;
  DECLARE SCHEMA_NAME ANCHOR SYSCAT.SCHEMATA.SCHEMANAME;
  DECLARE SENTENCE ANCHOR DB2UNIT_1B.MAX_VALUES.SENTENCE;
  DECLARE STMT STATEMENT;
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' SET ID = 0;
  SET EXPECTED_MSG = 'Previous execution ID (PREV_EXEC_ID) and a test name '
    || '(PROC_NAME) were given (5, Test_14)';
  SET SCHEMA_NAME = 'TEST_DB2UNIT_EXECUTION_TEST_14';

  CALL DB2UNIT_1B.DB2UNIT.RUN_SUITE(SCHEMA_NAME, 5, 'Test_14');

  SET SENTENCE = 'SET ? = (SELECT MESSAGE_REPORT '
    || 'FROM DB2UNIT_1B.EXECUTION_REPORTS '
    || 'WHERE DATE = (SELECT MAX(DATE) '
    || 'FROM DB2UNIT_1B.EXECUTION_REPORTS))';
  CALL LOGGER.ERROR(MESSAGE => SENTENCE);
  PREPARE STMT FROM SENTENCE;
  EXECUTE STMT INTO ACTUAL_MSG;

  CALL DB2UNIT_1B.DB2UNIT.ASSERT_STRING_EQUALS(EXPECTED_MSG, ACTUAL_MSG);
 END @

SELECT VARCHAR(SUBSTR(DIAGTEXT, 1, 128), 128) FROM ERRORSCHEMA.ERRORTABLE_2 @
SELECT VARCHAR(SUBSTR(DIAGTEXT, 1, 128), 128) FROM ERRORSCHEMA.ERRORTABLE_3 @
SELECT VARCHAR(SUBSTR(DIAGTEXT, 1, 128), 128) FROM ERRORSCHEMA.ERRORTABLE_4 @
SELECT VARCHAR(SUBSTR(DIAGTEXT, 1, 128), 128) FROM ERRORSCHEMA.ERRORTABLE_5 @
SELECT VARCHAR(SUBSTR(DIAGTEXT, 1, 128), 128) FROM ERRORSCHEMA.ERRORTABLE_6 @
SELECT VARCHAR(SUBSTR(DIAGTEXT, 1, 128), 128) FROM ERRORSCHEMA.ERRORTABLE_7 @
SELECT VARCHAR(SUBSTR(DIAGTEXT, 1, 128), 128) FROM ERRORSCHEMA.ERRORTABLE_8 @
SELECT VARCHAR(SUBSTR(DIAGTEXT, 1, 128), 128) FROM ERRORSCHEMA.ERRORTABLE_9 @
SELECT VARCHAR(SUBSTR(DIAGTEXT, 1, 128), 128) FROM ERRORSCHEMA.ERRORTABLE_10 @
SELECT VARCHAR(SUBSTR(DIAGTEXT, 1, 128), 128) FROM ERRORSCHEMA.ERRORTABLE_11 @
SELECT VARCHAR(SUBSTR(DIAGTEXT, 1, 128), 128) FROM ERRORSCHEMA.ERRORTABLE_12 @
SELECT VARCHAR(SUBSTR(DIAGTEXT, 1, 128), 128) FROM ERRORSCHEMA.ERRORTABLE_13 @
SELECT VARCHAR(SUBSTR(DIAGTEXT, 1, 128), 128) FROM ERRORSCHEMA.ERRORTABLE_14 @

DROP TABLE ERRORSCHEMA.ERRORTABLE_2 @
DROP TABLE ERRORSCHEMA.ERRORTABLE_3 @
DROP TABLE ERRORSCHEMA.ERRORTABLE_4 @
DROP TABLE ERRORSCHEMA.ERRORTABLE_5 @
DROP TABLE ERRORSCHEMA.ERRORTABLE_6 @
DROP TABLE ERRORSCHEMA.ERRORTABLE_7 @
DROP TABLE ERRORSCHEMA.ERRORTABLE_8 @
DROP TABLE ERRORSCHEMA.ERRORTABLE_9 @
DROP TABLE ERRORSCHEMA.ERRORTABLE_10 @
DROP TABLE ERRORSCHEMA.ERRORTABLE_11 @
DROP TABLE ERRORSCHEMA.ERRORTABLE_12 @
DROP TABLE ERRORSCHEMA.ERRORTABLE_13 @
DROP TABLE ERRORSCHEMA.ERRORTABLE_14 @

